#  ,                    
# /|   / o              
#  |__/    _|__|_       
#  | \   |  |  |  |   | 
#  |  \_/|_/|_/|_/ \_/|/
#                    /| 
#                    \| 
# Configuration
# Fonts
font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
                                                            
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
cursor_shape block
# Scroll-back
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
# OS Window
remember_window_size        no
initial_window_width        950
initial_window_height       500
window_padding_width        10
hide_window_decorations     no
dynamic_background_opacity  yes
confirm_os_window_close     0
# Selection
selection_foreground        none
selection_background        none
# Tabs
tab_bar_style               powerline
tab_bar_margin_width        5.0
tab_bar_margin_height       5.0 1.0
tab_bar_edge                top
tab_bar_min_tabs            1
tab_activity_symbol         ""
tab_bell_symbol             "󰵛"
# Mappings
map f5                      load_config_file
map ctrl+f5                    debug_config
map ctrl+y                  send_text y
map ctrl+shift+y            send_text yes\r
map ctrl+n                  send_text n
map ctrl+shift+n            send_text no\r
map ctrl+d                  quit
map ctrl+c                  copy_or_interrupt
map ctrl+x                  clear_selection
map ctrl+alt+c              copy_ansi_to_clipboard
map ctrl+v                  paste_from_clipboard
map ctrl+shift+o            launch codium .
map ctrl+shift+l            show_last_command_output
map ctrl+shift+c            clear_terminal reset active
map ctrl+shift+n            goto_layout horizontal
map ctrl+shift+m            goto_layout vertical
# Includes
include $HOME/.config/ml4w/settings/kitty-cursor-trail.conf
include colors-matugen.conf
include ./custom.conf
